# Generated by Django 4.2.7 on 2024-01-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_product_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_detail',
            field=models.CharField(default='', max_length=500),
        ),
    ]
