# Generated by Django 4.2.7 on 2024-01-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_detail',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
