# Generated by Django 4.2.7 on 2024-03-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_order_order_lasteditor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_id',
        ),
    ]
