# Generated by Django 4.2.7 on 2023-11-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productcategory_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='id',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, default='2023-11-21', null=True),
        ),
    ]
