# Generated by Django 4.2.7 on 2024-03-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_order_amount_orderitem_product_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_lastEditor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_user',
        ),
        migrations.AddField(
            model_name='order',
            name='order_table',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
