# Generated by Django 4.2.7 on 2024-03-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_rename_order_orderitem_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_lastUpdateTime',
            field=models.DateField(blank=True, default='2024-03-10', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, default='2024-03-10', null=True),
        ),
    ]
