# Generated by Django 4.2.7 on 2024-03-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_product_orderitem_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_lastUpdateDate',
            field=models.DateField(blank=True, default='2024-03-12', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_lastUpdateTime',
            field=models.TimeField(blank=True, default='13:32:28', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, default='2024-03-12', null=True),
        ),
    ]
