# Generated by Django 4.2.7 on 2024-03-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_productcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(blank=True, default='2024-03-17', null=True),
        ),
    ]
